allowBuilds:
  electron: true
  esbuild: false
  msgpackr-extract: false

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAgeExclude:
  - myde-xcb@0.1.0 || 0.1.1
  - myde-remote-connect@0.0.5
  - myde-ui@0.0.4 || 0.0.5 || 0.0.7
  - myde-input@1.0.1

onlyBuiltDependencies:
  - '@biomejs/biome'
  - electron
