allowBuilds:
  electron: true
  esbuild: false

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAgeExclude:
  - myde-xcb@0.1.0
  - myde-xcb@0.1.1
  - myde-remote-connect@0.0.5

onlyBuiltDependencies:
  - '@biomejs/biome'
  - electron

patchedDependencies:
  dkh-ui@0.14.2: patches/dkh-ui@0.14.2.patch
