allowBuilds:
  electron: true
  esbuild: false

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAgeExclude:
  - myde-xcb@0.1.0
  - myde-xcb@0.1.1

onlyBuiltDependencies:
  - '@biomejs/biome'
  - electron
